apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod

on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: go-oct
          artifact-id: fd50ab1e-9fe7-4cb8-afc7-45c6d1c36dba
          target-environment: aspm_qa
