apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod

on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: go-oct
          artifact-id: a7e0d5f0-0244-4e37-aa31-cf8213105df6
          target-environment: aspm_qa
